ALTER TABLE stores DROP COLUMN address;
ALTER TABLE stores ADD COLUMN prefecture VARCHAR(255) NOT NULL;
ALTER TABLE stores ADD COLUMN city VARCHAR(255) NOT NULL;
ALTER TABLE stores ADD COLUMN street VARCHAR(255) NOT NULL;